### ISSUE TITLE
angular-user-idle breaks in AOT mode

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [rednez/angular-user-idle#3]
Hi @rednez ,
Thank-you for this nice module.  I would like to share some of the error logs I get when the application is run in AOT.  Please find the snapshots attached .  Please let me know if there are any work-arounds.
<img width="959" alt="snapshot1" src="https://user-images.githubusercontent.com/28565587/33303519-95827b76-d429-11e7-82c7-d67c56e52297.PNG">
<img width="934" alt="snapshot2" src="https://user-images.githubusercontent.com/28565587/33303521-95deb968-d429-11e7-9b14-4724ff6a7c58.PNG">
<img width="959" alt="snapshot3" src="https://user-images.githubusercontent.com/28565587/33303522-9948a3ca-d429-11e7-9b65-bc181400e156.PNG">

**Comment by costaivo** [comment]
The node module does not have the ts files included, which causes the above error.
It has only *.d.ts files
To fix the error i manually downloaded the files from the git project and pasted inside the **node_modules\angular-user-idle**

- user-idle.config.ts
- user-idle.module.ts
- user-idle.service.ts
- user-idle.ts

**Comment by rednez** [comment]
Check new version 1.1.0.

**Comment by ibrahimsen** [comment]
Still same with version 1.1.0.

**Comment by ibrahimsen** [comment]
`ERROR in ./node_modules/angular-user-idle/user-idle.config.ts
Module build failed: Error: "ProdDir\ui\node_modules\angular-user-idle\user-idle.config.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library.
Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).`

**Comment by Yogeshwar1992** [comment]
Hi  Sir 
@ibrahimsen, 

did you solved above issues. if yeas,  could you please help me out in this my project is on angular 5

thanks in advance :)

**Comment by nehaagrawala** [comment]
Hi,
How to set idleTime value in Angular 5.x?

**Comment by jrafael83** [comment]
OK, I had the same issue, I was unable to update the application to Angular 6 (the version of this package for Angular 6 works fine), because it is a very large app and for some other reasons. The problem here is that the package is not correctly formatted to be use as a Prod Package, according to: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit

So, I had two options: Contribute and correct the package (which is what I should do to help others who can only use Angular 5), or solve the issue with my app as fast as I can. Well, I took the easy path which is this:

Open your application **node_modules** folder and find the folder **angular-user-idle** grab the following files from it:
**user-idle-config.ts**
**user-idle-module.ngfactory.d.ts** (probably nor required)
**user-idle-module.ts**
**user-idle.service.ts**
**user-idle.ts**

Create a folder within your **clientApp** folder, for ex: **angular-user-idle** and put the files there.
(in my case I used components/shared/modules/angular-user-idle).

Now, uninstall the **angular-user-idle** package ("npm uninstall angular-user-idle").

Instead of importing the module as "angular-user-idle".

Import it like this:
**import { UserIdleModule } from './components/shared/modules/angular-user-idle/user-idle';**

The rest of the configurations will work the same, just that now the package is not a package but a module within your app.

I hope this help others.
