### ISSUE TITLE
Error after upgrading to Angular 10

### ISSUE THREAD

**Issue by bandman0226** [rednez/angular-user-idle#98]
When trying to serve I am seeing:
Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

**Comment by toski112** [comment]
Same problem, any ideas?

**Comment by bandman0226** [comment]
Not sure still if its a "good" fix but in my app.module.ts file I added this just underneath the imports:

`declare module '@angular/core' {
    interface ModuleWithProviders<T = any> {
        ngModule: Type<T>;
        providers?: Provider[];
    }
}`

**Comment by toski112** [comment]
@bandman0226 Thanks. I hope it will be corrected by the author.

**Comment by rednez** [comment]
Please, provide exact steps to reproduce the problem. Because I try to
1. `ng new test-app`
2. `npm install angular-user-idle`
3. Set lib in app's module and use it in app component (just for test).
4. try `ng serve`, `ng build` and `ng build --prod` 
and see NO warnings NO errors. All it's OK.

I use ### angular-user-idle in five commercial projects based on Angular 10/11 and never faced the described problems.

**Comment by sdancer** [comment]
@bandman0226 I just upgraded Angular from 9 to 11.  It seems like your fix resolved it for me.

**Comment by toski112** [comment]
> Please, provide exact steps to reproduce the problem. Because I try to
> 
> 1. `ng new test-app`
> 2. `npm install angular-user-idle`
> 3. Set lib in app's module and use it in app component (just for test).
> 4. try `ng serve`, `ng build` and `ng build --prod`
>    and see NO warnings NO errors. All it's OK.
> 
> I use ### angular-user-idle in five commercial projects based on Angular 10/11 and never faced the described problems.

Problem is when you use angular-user-idle in library not in a project.

Builder in library is different, it is : "@angular-devkit/build-angular:ng-packagr".

**Comment by MaiGhoneem** [comment]
i have same problem @bandman0226 thanks, your solution fix it
